language: cpp
addons:
  apt:
    packages:
      - g++-7
      - clang-6.0
      - xorg-dev
      - libc++-dev
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-6.0
matrix:
  include:
    - name: Linux GCC
      env: LABEL=LinuxGCC
      os: linux
      dist: xenial
      sudo: required
      before_script:
        - CC=gcc-7
        - CXX=g++-7
    - name: Linux Clang
      env: LABEL=LinuxClang
      os: linux
      dist: xenial
      sudo: required
      before_script:
        - CC=clang-6.0
        - CXX=clang++-6.0
    - name: Windows MSVC
      env: LABEL=WindowsMSVC
      os: windows
      install:
        - choco install python3
    - name: OS X
      env: LABEL=OSX
      os: osx
      osx_image: xcode10.1
script:
  - mkdir build && cd build
  - if [ "$TRAVIS_OS_NAME" == "linux" ];   then cmake ..; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ];     then cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 ..; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then cmake -G "Visual Studio 15 2017 Win64" -DPYTHON_EXECUTABLE=/c/Python37/python.exe ..; fi
  - cmake --build .
