language: cpp
addons:
  apt:
    packages:
      - g++-7
      - clang-6.0
      - xorg-dev
      - libc++-dev
      - lcov
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-6.0
matrix:
  include:
    - name: Linux GCC
      env: LABEL=LinuxGCC
      os: linux
      dist: xenial
      sudo: required
      install:
        - gem install coveralls-lcov
      before_script:
        - CC=gcc-7
        - CXX=g++-7
        - INSTALL_TARGET_NAME=install
    - name: Linux Clang
      env: LABEL=LinuxClang
      os: linux
      dist: xenial
      sudo: required
      before_script:
        - CC=clang-6.0
        - CXX=clang++-6.0
        - INSTALL_TARGET_NAME=install
    - name: Windows MSVC
      env: LABEL=WindowsMSVC
      os: windows
      install:
        - choco install python3
      before_script:
        - INSTALL_TARGET_NAME=INSTALL
    - name: OS X
      env: LABEL=OSX
      os: osx
      osx_image: xcode10.1
      before_script:
        - INSTALL_TARGET_NAME=install
script:
  - mkdir build && cd build
  - if [ "$TRAVIS_OS_NAME" == "linux" ];   then cmake -DCMAKE_INSTALL_PREFIX=install -DILLUSION_CODE_COVERAGE=On -DCMAKE_BUILD_TYPE=Debug ..; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ];     then cmake -DCMAKE_INSTALL_PREFIX=install -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 ..; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then cmake -DCMAKE_INSTALL_PREFIX=install -G "Visual Studio 15 2017 Win64" -DPYTHON_EXECUTABLE=/c/Python37/python.exe ..; fi
  - cmake --build . --parallel 4 --target $INSTALL_TARGET_NAME && cd ..
  - if [ "$CXX" == "g++-7" ]; then ./lcov.sh; fi
  - if [ "$CXX" == "g++-7" ]; then ./build/install/bin/GPUInfo.sh; fi
  - if [ "$CXX" == "g++-7" ]; then ./build/install/bin/Headless.sh; fi
  - if [ "$CXX" == "g++-7" ]; then coveralls-lcov build/coverage.info; fi
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/55e8e7aa87bb2d989407
    on_success: change
    on_failure: always
    on_start: never
